
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmrpxltbqbqzepxjejba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcnB4bHRicWJxemVweGplamJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjQ3MDIsImV4cCI6MjA1ODc0MDcwMn0.LDUEKuBxRUTvJvXfRYb58A_m1yL9lCk_O5UOIwtLDJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to handle common error cases
export const handleSupabaseError = (error: any) => {
  console.error('Supabase error:', error);
  
  // Return user-friendly error messages based on error type
  if (error?.code === 'PGRST116') {
    return 'Dados não encontrados.';
  } else if (error?.code?.includes('23505')) {
    return 'Este registro já existe.';
  } else if (error?.message?.includes('timeout')) {
    return 'Tempo de conexão esgotado. Verifique sua internet e tente novamente.';
  } else if (error?.message?.includes('JWT')) {
    return 'Erro de autenticação. Por favor, faça login novamente.';
  } else if (error?.message?.includes('password')) {
    return 'Senha incorreta ou formato inválido.';
  } else if (error?.message?.includes('email')) {
    return 'E-mail inválido ou já registrado.';
  }
  
  return error?.message || 'Ocorreu um erro ao processar sua solicitação.';
};
